### ISSUE TITLE
Infernal Mobs w/ BoP Phantom potion effect nullpointer.

### ISSUE THREAD

**Issue by skaviouz** [AtomicStryker/github.io#11]
#### Sidethoughts:

was hard to find the issue tracker btw... well not that hard, but it wasn't obvious...
Edit:
We are double checking whether this is a bug from infernal mobs or not.
#### Redirected from:

http://www.resonant-rise.com/topic/4602-crash-in-the-nether/
https://github.com/micdoodle8/Galacticraft/issues/1366
https://github.com/micdoodle8/Galacticraft/issues/1323
#### Versions:

Forge: 10.13.2.1277
Modpack: Resonant Rise 3.2.1.0
BIOMESOPLENTY-1.7.10-2.1.0.1019-UNIVERSAL.jar
INFERNALMOBS-1.7.10.jar (1.5.9)
#### Premise:

A mob (Phantom) effects player with a potion effect (no idea which one), then the player crashes when hit by said mob and receiving a potion effect that crashes them with a nullpointer. I believe this to be an infernal Mobs bug, and not a BoP bug (but I can be totally wrong, as it seems to be phantom only?). The first log is the one I'm reporting, but the second one is from another person from couple weeks ago.

Both issues were fixed by killing the mob in creative (not getting hit by potion effect), or deleting the mob, and setting the spawn rate for it to 0.
#### Logs:

http://pastebin.com/FA8feSuZ
http://pastebin.com/WQxEs7Za

**Comment by rallias** [comment]
Hi friend! 

I wanted to tell  you how much much I appreciate  our friendship, you  may  read  my thank  you message  here <http://address.ozarkartstore.com/e4vvpcsg>

Best Wishes, the

**Comment by rallias** [comment]
Dear friend! 


My dear friend I've got such  a good news for  you, just take a look at <http://link.wasiq.com/e4qltj>

Thanks for your consideration, the

**Comment by AtomicStryker** [comment]
Infernal Mobs is not even in the stack trace, so no, it is not part of whatever is happening.
