### ISSUE TITLE
Advanced Machines startup crash - TileEntityAdvancedExtractor

### ISSUE THREAD

**Issue by Darkos333** [AtomicStryker/github.io#12]
Crash report:
http://pastebin.com/68r2wAsu
Full fml log:
http://www36.zippyshare.com/v/kB3RowHb/file.html

**Comment by AtomicStryker** [comment]
IC2 devs have changed TileEntity.updateEntity() method to be final, which causes my class overriding it to fail on load. Current fix: Dont use newer versions.

**Comment by AtomicStryker** [comment]
Fixed in Advanced Machines 1.1.5, available now

**Comment by rallias** [comment]
Dear, 

There is something super interesting for you,  just take  a look, you'll never regret. Please,  read  more here <http://after.techunboxing.com/e4ybah>

Later, the
