### ISSUE TITLE
[1.7.10] RuinsTrigger doesn't trigger with FastCraft installed.

### ISSUE THREAD

**Issue by DarianLStephens** [AtomicStryker/github.io#13]
As in the title, the RuinsTrigger command block argument doesn't happen if FastCraft is installed. I don't know if you guys can do anything about it since FastCraft is weird, and I'm not sure if you'll even consider an update to 1.7.10, but it is a big problem, and I appreciate you even looking at this issue.

Tested by: Installing Ruins mod, installing FastCraft, and spawning a ruin with a RuinsTrigger command block. The block will fail to run, and remain in place.

**Comment by AtomicStryker** [comment]
No, i don't support 1710 anymore. This came up before. As far i recall, FastCraft did not trigger the Forge/FML event Ruins utilizes for RuinsTrigger (PlayerEnteredChunk?).
